### PR TITLE
fix: Bug #361 fix for segfault on mqtt configuring

### PR DESCRIPTION
**Pull request by nil4git**
This fix is for seq fault occured while configuring mqtt message queue

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by nil4git** [comment]
@iain-anderson  : Kindly review
With this fix, the seg fault crash is gone and mqtt message queue publish functionality is working as well

**Comment by iain-anderson** [comment]
timeout should be based on `EDGEX_STARTUP_DURATION` and `EDGEX_STARTUP_INTERVAL` values. I'm working on a PR that applies these in various parts of the startup including mqtt connection.

**Comment by iain-anderson** [comment]
See draft PR #365

**Comment by iain-anderson** [comment]
Issue addressed in #365 - closing

**Pull request closed without merging**
