### PR TITLE
Issue 308

### PR DESCRIPTION
**Pull request by iain-anderson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

* default values of CheckInterval and ProfilesDir result in run-time errors
* data type names are inconsistent with the definitions in go-mod-core-contracts
* arbitrarily large http requests may be made resulting in potential DoS

## What is the new behavior?
Checks added for CheckInterval, ProfilesDir being unset
Changed type names
Added MaxRequestSize configuration option and enforced in http processing

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No
Type names in device profiles are now case-sensitive (in practice this ~~is a breaking change in core-metadata where they will be validated~~ should not be an issue as they are normalised in core-metadata)

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by SteveOss — COMMENTED** [review]
@iain-anderson In edgex_propertytype_tostring have replaced strcasecmp with strcmp, does this mean type names are now case sensitive ?

**Comment by iain-anderson** [comment]
> @iain-anderson In edgex_propertytype_tostring have replaced strcasecmp with strcmp, does this mean type names are now case sensitive ?

Yes but they should be normalized during validation in core-metadata [(code here)](https://github.com/edgexfoundry/go-mod-core-contracts/blob/9f18a04425995e91a47311f98a0a925ff51ed9a1/v2/utils.go#L28)

**Comment by SteveOss** [comment]
@iain-anderson And this is the only path to this function ?

**Comment by iain-anderson** [comment]
@SteveOss  it will only be used when receiving a device profile update notification from metadata, or when requesting a device profile from metadata (when a device is instantiated for which we don't yet have the profile definition)

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
