### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by iain-anderson**
Example config files: use single quote for strings, increase retry count (as per other services)
Metadata client: URL-escape entity names that might need it

### CODE REVIEW

**Comment by SteveOss** [comment]
@iain-anderson Not sure what's caused the build failure ?

**Comment by iain-anderson** [comment]
recheck

**Comment by SteveOss** [comment]
@iain-anderson Did recheck do anything ?

**Comment by iain-anderson** [comment]
No. commit --amend and push --force does the job, but that invalidates the review as you can see

**Pull request merged**
