### PR TITLE
config overwrite feature based on fuji branch

### PR DESCRIPTION
**Pull request by drensber**
Signed-off-by: davidr@beechwoods.com <davidr@beechwoods.com>

### CODE REVIEW

**Comment by drensber** [comment]
> This looks fine except:
> 
> * Please don't use tabs or trailing '{' symbols
> * The argument-consumption logic looks wrong for the new option: as it takes no parameter, the call to testBool() should be in its own else-if block with an associated consumeArgs (...., 1);

Iain, you're correct about the separate block and different argument to consumeArgs (I think I never encountered that in testing, because I always made --overwrite the last argument).  I'll correct that and that lines that have extraneous spaces/tabs.

**Comment by drensber** [comment]
> This looks fine except:
> 
> * Please don't use tabs or trailing '{' symbols
> * The argument-consumption logic looks wrong for the new option: as it takes no parameter, the call to testBool() should be in its own else-if block with an associated consumeArgs (...., 1);

What do you mean by trailing '{' symbols?

**Comment by iain-anderson** [comment]
recheck

**Comment by iain-anderson** [comment]
@drensber Can you add a "Changes for 1.1.1" section to the CHANGES file, with an entry indicating that -overwrite is now implemented, and bump the version in the VERSION file also. Hopefully we'll have the CI up and running soon.
Thanks

**Comment by drensber** [comment]
Done.

**Pull request merged**
