### PR TITLE
Add example Makefile to example device service

### PR DESCRIPTION
**Pull request by mhall119**
To help new developers get started writing a device service in C, include an example Makefile that will build the template.c file provided as an example.

### CODE REVIEW

**Comment by iain-anderson** [comment]
Can we just have the file as Makefile rather than example.Makefile?
Also please add a README that just says 1) you can build the example using make and the Makefile provided 2) but you'll need to set CSDK_DIR and 3) more information is in the Getting Started guide (in device-sdk-go - with link to the pdf if we have the artefact available?)

**Comment by mhall119** [comment]
If having it named Makefile won't cause any problems or confusion within the device-sdk-c project, I can do that.

**Comment by JPWKU** [comment]
recheck

**Comment by SteveOss** [comment]
@mhall119 As CMake always builds "out of source" i.e. in it's own directory, no danger of a Makefile conflict.

**Pull request merged**
