### PR TITLE
F-69 Add registry abstraction and port consul implementation to it.

### PR DESCRIPTION
**Pull request by iain-anderson**
Addresses #69

### CODE REVIEW

**Comment by MightyNerdEric** [comment]
recheck

**Comment by MightyNerdEric** [comment]
For now, please ignore the "CMake Verify" check. It shouldn't be showing up at all. I'll get it fixed as soon as possible, but this and any other PR where it shows up should be considered successful as long as all other builds succeeded.

**Comment by MightyNerdEric** [comment]
recheck

**Comment by jamesrgregg** [comment]
@iain-anderson this was resolved by @MightyNerdEric after enabling the proper checks on the branch protection for the repo.

**Pull request merged**
