### PR TITLE
feat!: Publish System Events for device discovery and add discovery request ID

### PR DESCRIPTION
**Pull request by Tylerg2471**
BREAKING CHANGE: Discovery function takes in request_id parameter now
Add request ID for discovery requests
Update to allow event publishing from a discovery function

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## New Dependency Instructions (If applicable)

### CODE REVIEW

**Comment by cloudxxx8** [comment]
for the breaking change, the commit message and pr title should start with `feat!: `

**Comment by Tylerg2471** [comment]
> for the breaking change, the commit message and pr title should start with `feat!: `

@cloudxxx8 Should the "BREAKING CHANGE" statement also be included in the title/commit messages?

**Comment by cloudxxx8** [comment]
no,  "BREAKING CHANGE" statement should be in the commit message body and PR descirption, not title

**Review by iain-anderson — APPROVED** [review]
LGTM

**Pull request merged**
